---
name: Deploy blog to GitHub Pages

on:
  push:
    branches: ["main"]
    paths:
      - "content/**"
      - "pelicanconf.py"
      - "poetry.local"
      - "publishconfig.py"
      - "pyproject.toml"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install Poetry
        run: |
          pip install poetry
          poetry env use 3.11
          poetry install
      - name: Build blog
        run: |
          poetry run pelican content -s publishconf.py
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'output/'
  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: github-pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
